import = [
  "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16
